---
# bring stack down
- hosts: loadbalancer
  become: yes
  tasks:
    - service:
        name=nginx
        state=stopped
    - wait_for:
        port=80
        state=drained

- hosts: webserver
  become: yes
  tasks:
    - service:
        name=apache2
        state=stopped
    - wait_for:
        port=80
        state=stopped

# restart mysql
- hosts: database
  become: yes
  tasks:
    - service:
        name=mysql
        state=restarted
    - wait_for:
        host={{ ansible_eth0.ipv4.address }}
        port=3306
        state=started

# bring stack up
- hosts: webserver
  become: yes
  tasks:
    - service:
        name=apache2
        state=started
    - wait_for:
        port=80

- hosts: loadbalancer
  become: yes
  tasks:
    - service:
        name=nginx
        state=started
    - wait_for:
        port=80
